on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Build and Publish

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Setup
      - uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - name: Install Yarn package manager
        run: npm install -g yarn
      - name: Install dependencies and check their integrity
        run: |
          yarn install
      # Test
      - name: Lint code
        run: yarn lint
      - name: Run tests
        run: yarn test

      # Publish
      - name: "Get Short Sha Hash"
        id: get-short-sha
        uses: actions/github-script@v6.4.0
        with:
          script: |
            const shortSha = context.sha.substring(0, 7)
            core.setOutput('shortSha', shortSha)
      - name: 'Get Commit Timestamp'
        id: get-timestamp
        run: |
          TIMESTAMP=$(git log -1 --format='%cI' | sed -e's/[-T:]//g' -e's/+.*$//g')
          echo "::set-output name=timestamp::$TIMESTAMP"
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/ccd/definition-processor:pr-${{github.event.number}}-${{ steps.get-short-sha.outputs.shortSha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/ccd/definition-processor:pr-${{github.event.number}}-${{ steps.get-short-sha.outputs.shortSha }}
        if: startsWith(github.ref, 'refs/pull')
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/ccd/definition-processor:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/ccd/definition-processor:latest
        if: github.ref == 'refs/heads/master'
